package examples.fixed2free.integration;

import java.util.ArrayList;
import java.util.List;

public class MockTableInfoProvider implements TableInfoProvider {

	@Override
	public List<ColumnInfo> getColumns(String tableName) {
		if (tableName.equalsIgnoreCase("INDATEP")){
			return doIndatep();
		}
		return null;
	}

	private List<ColumnInfo>doInddesp(String schema){
		ArrayList<ColumnInfo> result = new ArrayList<ColumnInfo>();
		result.add(doINDDESPColumn1(result, schema));
		result.add(doINDDESPColumn2(result, schema));
		result.add(doINDDESPColumn3(result, schema));
		result.add(doINDDESPColumn4(result, schema));
		result.add(doINDDESPColumn5(result, schema));
		result.add(doINDDESPColumn6(result, schema));
		result.add(doINDDESPColumn7(result, schema));
		result.add(doINDDESPColumn8(result, schema));
		result.add(doINDDESPColumn9(result, schema));
		result.add(doINDDESPColumn10(result, schema));
		result.add(doINDDESPColumn11(result, schema));
		result.add(doINDDESPColumn12(result, schema));
		result.add(doINDDESPColumn13(result, schema));
		result.add(doINDDESPColumn14(result, schema));
		result.add(doINDDESPColumn15(result, schema));
		result.add(doINDDESPColumn16(result, schema));
		result.add(doINDDESPColumn17(result, schema));
		result.add(doINDDESPColumn18(result, schema));
		result.add(doINDDESPColumn19(result, schema));
		result.add(doINDDESPColumn20(result, schema));
		return result;
	}
	private ColumnInfo doINDDESPColumn1(ArrayList<ColumnInfo> result,
			String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DDDEPT");
		temp.setTableName("INDDESP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(1);
		temp.setDataType(ColumnInfo.NUMERIC);
		temp.setLength(2);
		temp.setNumericScale(new Integer(0));
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("DEPT");
		temp.setStorage(2);
		temp.setNumericPrecision(new Integer(2));
		temp.setCCSID(null);
		temp.setTableSchema(schema);
		temp.setColumnDefault("0");
		temp.setCharacterMaximumLength(null);
		temp.setCharacterOctetLength(null);
		temp.setNumericPrecisionRadix(new Integer(10));
		temp.setDateTimePrecision(null);
		temp.setColumnText("DEPARTMENT NUMBER");
		temp.setSystemColumnName("DDDEPT");
		temp.setSystemTableName("INDDESP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDDESPColumn2(ArrayList<ColumnInfo> result,
			String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DDDESL");
		temp.setTableName("INDDESP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(2);
		temp.setDataType(ColumnInfo.CHAR);
		temp.setLength(20);
		temp.setNumericScale(null);
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("DESL");
		temp.setStorage(20);
		temp.setNumericPrecision(null);
		temp.setCCSID(new Integer(37));
		temp.setTableSchema(schema);
		temp.setColumnDefault(" ");
		temp.setCharacterMaximumLength(new Integer(20));
		temp.setCharacterOctetLength(new Integer(20));
		temp.setNumericPrecisionRadix(null);
		temp.setDateTimePrecision(null);
		temp.setColumnText("LONG DEPT DESC");
		temp.setSystemColumnName("DDDESL");
		temp.setSystemTableName("INDDESP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDDESPColumn3(ArrayList<ColumnInfo> result,
			String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DDDESS");
		temp.setTableName("INDDESP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(3);
		temp.setDataType(ColumnInfo.CHAR);
		temp.setLength(9);
		temp.setNumericScale(null);
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("DESS");
		temp.setStorage(9);
		temp.setNumericPrecision(null);
		temp.setCCSID(new Integer(37));
		temp.setTableSchema(schema);
		temp.setColumnDefault(" ");
		temp.setCharacterMaximumLength(new Integer(9));
		temp.setCharacterOctetLength(new Integer(9));
		temp.setNumericPrecisionRadix(null);
		temp.setDateTimePrecision(null);
		temp.setColumnText("SHORT DEPT DESC");
		temp.setSystemColumnName("DDDESS");
		temp.setSystemTableName("INDDESP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDDESPColumn4(ArrayList<ColumnInfo> result,
			String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DDLOSB");
		temp.setTableName("INDDESP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(4);
		temp.setDataType(ColumnInfo.DECIMAL);
		temp.setLength(5);
		temp.setNumericScale(new Integer(2));
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("LOW%");
		temp.setStorage(3);
		temp.setNumericPrecision(new Integer(5));
		temp.setCCSID(null);
		temp.setTableSchema(schema);
		temp.setColumnDefault("0");
		temp.setCharacterMaximumLength(null);
		temp.setCharacterOctetLength(null);
		temp.setNumericPrecisionRadix(new Integer(10));
		temp.setDateTimePrecision(null);
		temp.setColumnText("LOW% FOR SB CALC");
		temp.setSystemColumnName("DDLOSB");
		temp.setSystemTableName("INDDESP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}

	private List<ColumnInfo>doIndatep(String schema){
		ArrayList<ColumnInfo> result = new ArrayList<ColumnInfo>();
		result.add(doINDATEPColumn1(result, schema));
		result.add(doINDATEPColumn2(result, schema));
		result.add(doINDATEPColumn3(result, schema));
		result.add(doINDATEPColumn4(result, schema));
		result.add(doINDATEPColumn5(result, schema));
		result.add(doINDATEPColumn6(result, schema));
		result.add(doINDATEPColumn7(result, schema));
		result.add(doINDATEPColumn8(result, schema));
		result.add(doINDATEPColumn9(result, schema));
		result.add(doINDATEPColumn10(result, schema));
		result.add(doINDATEPColumn11(result, schema));
		result.add(doINDATEPColumn12(result, schema));
		result.add(doINDATEPColumn13(result, schema));
		result.add(doINDATEPColumn14(result, schema));
		result.add(doINDATEPColumn15(result, schema));
		return result;
	}
	private List<ColumnInfo> doIndatep() {
		return doIndatep("THELIB");
	}

	private ColumnInfo doINDATEPColumn1(ArrayList<ColumnInfo> result, String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DAWEEK");
		temp.setTableName("INDATEP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(1);
		temp.setDataType(ColumnInfo.NUMERIC);
		temp.setLength(1);
		temp.setNumericScale(new Integer(0));
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("WEEK");
		temp.setStorage(1);
		temp.setNumericPrecision(new Integer(1));
		temp.setCCSID(null);
		temp.setTableSchema(schema);
		temp.setColumnDefault("0");
		temp.setCharacterMaximumLength(null);
		temp.setCharacterOctetLength(null);
		temp.setNumericPrecisionRadix(new Integer(10));
		temp.setDateTimePrecision(null);
		temp.setColumnText("WEEK OF PERIOD");
		temp.setSystemColumnName("DAWEEK");
		temp.setSystemTableName("INDATEP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDATEPColumn2(ArrayList<ColumnInfo> result, String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DAPER");
		temp.setTableName("INDATEP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(2);
		temp.setDataType(ColumnInfo.NUMERIC);
		temp.setLength(2);
		temp.setNumericScale(new Integer(0));
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("PERIOD");
		temp.setStorage(2);
		temp.setNumericPrecision(new Integer(2));
		temp.setCCSID(null);
		temp.setTableSchema(schema);
		temp.setColumnDefault("0");
		temp.setCharacterMaximumLength(null);
		temp.setCharacterOctetLength(null);
		temp.setNumericPrecisionRadix(new Integer(10));
		temp.setDateTimePrecision(null);
		temp.setColumnText("PERIOD");
		temp.setSystemColumnName("DAPER");
		temp.setSystemTableName("INDATEP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDATEPColumn3(ArrayList<ColumnInfo> result, String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DADAY");
		temp.setTableName("INDATEP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(3);
		temp.setDataType(ColumnInfo.DECIMAL);
		temp.setLength(1);
		temp.setNumericScale(new Integer(0));
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("DAY");
		temp.setStorage(1);
		temp.setNumericPrecision(new Integer(1));
		temp.setCCSID(null);
		temp.setTableSchema(schema);
		temp.setColumnDefault("0");
		temp.setCharacterMaximumLength(null);
		temp.setCharacterOctetLength(null);
		temp.setNumericPrecisionRadix(new Integer(10));
		temp.setDateTimePrecision(null);
		temp.setColumnText("DAY OF WEEK MONDAY=1");
		temp.setSystemColumnName("DADAY");
		temp.setSystemTableName("INDATEP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDATEPColumn4(ArrayList<ColumnInfo> result, String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DAFYR");
		temp.setTableName("INDATEP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(4);
		temp.setDataType(ColumnInfo.NUMERIC);
		temp.setLength(2);
		temp.setNumericScale(new Integer(0));
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("FY");
		temp.setStorage(2);
		temp.setNumericPrecision(new Integer(2));
		temp.setCCSID(null);
		temp.setTableSchema(schema);
		temp.setColumnDefault("0");
		temp.setCharacterMaximumLength(null);
		temp.setCharacterOctetLength(null);
		temp.setNumericPrecisionRadix(new Integer(10));
		temp.setDateTimePrecision(null);
		temp.setColumnText("FISCAL YEAR");
		temp.setSystemColumnName("DAFYR");
		temp.setSystemTableName("INDATEP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDATEPColumn5(ArrayList<ColumnInfo> result, String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DAWDT1");
		temp.setTableName("INDATEP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(5);
		temp.setDataType(ColumnInfo.DECIMAL);
		temp.setLength(7);
		temp.setNumericScale(new Integer(0));
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("WDT1");
		temp.setStorage(4);
		temp.setNumericPrecision(new Integer(7));
		temp.setCCSID(null);
		temp.setTableSchema(schema);
		temp.setColumnDefault("0");
		temp.setCharacterMaximumLength(null);
		temp.setCharacterOctetLength(null);
		temp.setNumericPrecisionRadix(new Integer(10));
		temp.setDateTimePrecision(null);
		temp.setColumnText("WK1 ENDING DATE");
		temp.setSystemColumnName("DAWDT1");
		temp.setSystemTableName("INDATEP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDATEPColumn6(ArrayList<ColumnInfo> result, String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DAWDT2");
		temp.setTableName("INDATEP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(6);
		temp.setDataType(ColumnInfo.DECIMAL);
		temp.setLength(7);
		temp.setNumericScale(new Integer(0));
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("WDT2");
		temp.setStorage(4);
		temp.setNumericPrecision(new Integer(7));
		temp.setCCSID(null);
		temp.setTableSchema(schema);
		temp.setColumnDefault("0");
		temp.setCharacterMaximumLength(null);
		temp.setCharacterOctetLength(null);
		temp.setNumericPrecisionRadix(new Integer(10));
		temp.setDateTimePrecision(null);
		temp.setColumnText("WK2 ENDING DATE");
		temp.setSystemColumnName("DAWDT2");
		temp.setSystemTableName("INDATEP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDATEPColumn7(ArrayList<ColumnInfo> result, String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DAWDT3");
		temp.setTableName("INDATEP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(7);
		temp.setDataType(ColumnInfo.DECIMAL);
		temp.setLength(7);
		temp.setNumericScale(new Integer(0));
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("WDT3");
		temp.setStorage(4);
		temp.setNumericPrecision(new Integer(7));
		temp.setCCSID(null);
		temp.setTableSchema(schema);
		temp.setColumnDefault("0");
		temp.setCharacterMaximumLength(null);
		temp.setCharacterOctetLength(null);
		temp.setNumericPrecisionRadix(new Integer(10));
		temp.setDateTimePrecision(null);
		temp.setColumnText("WK3 ENDING DATE");
		temp.setSystemColumnName("DAWDT3");
		temp.setSystemTableName("INDATEP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDATEPColumn8(ArrayList<ColumnInfo> result, String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DAWDT4");
		temp.setTableName("INDATEP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(8);
		temp.setDataType(ColumnInfo.DECIMAL);
		temp.setLength(7);
		temp.setNumericScale(new Integer(0));
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("WDT4");
		temp.setStorage(4);
		temp.setNumericPrecision(new Integer(7));
		temp.setCCSID(null);
		temp.setTableSchema(schema);
		temp.setColumnDefault("0");
		temp.setCharacterMaximumLength(null);
		temp.setCharacterOctetLength(null);
		temp.setNumericPrecisionRadix(new Integer(10));
		temp.setDateTimePrecision(null);
		temp.setColumnText("WK4 ENDING DATE");
		temp.setSystemColumnName("DAWDT4");
		temp.setSystemTableName("INDATEP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDATEPColumn9(ArrayList<ColumnInfo> result, String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DAFYDT");
		temp.setTableName("INDATEP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(9);
		temp.setDataType(ColumnInfo.DECIMAL);
		temp.setLength(7);
		temp.setNumericScale(new Integer(0));
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("FYDT");
		temp.setStorage(4);
		temp.setNumericPrecision(new Integer(7));
		temp.setCCSID(null);
		temp.setTableSchema(schema);
		temp.setColumnDefault("0");
		temp.setCharacterMaximumLength(null);
		temp.setCharacterOctetLength(null);
		temp.setNumericPrecisionRadix(new Integer(10));
		temp.setDateTimePrecision(null);
		temp.setColumnText("FISCAL YEAR END DATE");
		temp.setSystemColumnName("DAFYDT");
		temp.setSystemTableName("INDATEP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDATEPColumn10(ArrayList<ColumnInfo> result, String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DASNDT");
		temp.setTableName("INDATEP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(10);
		temp.setDataType(ColumnInfo.DECIMAL);
		temp.setLength(7);
		temp.setNumericScale(new Integer(0));
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("SNDT");
		temp.setStorage(4);
		temp.setNumericPrecision(new Integer(7));
		temp.setCCSID(null);
		temp.setTableSchema(schema);
		temp.setColumnDefault("0");
		temp.setCharacterMaximumLength(null);
		temp.setCharacterOctetLength(null);
		temp.setNumericPrecisionRadix(new Integer(10));
		temp.setDateTimePrecision(null);
		temp.setColumnText("LAST SUNDAY");
		temp.setSystemColumnName("DASNDT");
		temp.setSystemTableName("INDATEP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDATEPColumn11(ArrayList<ColumnInfo> result, String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DAPCDT");
		temp.setTableName("INDATEP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(11);
		temp.setDataType(ColumnInfo.DECIMAL);
		temp.setLength(7);
		temp.setNumericScale(new Integer(0));
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("PCDT");
		temp.setStorage(4);
		temp.setNumericPrecision(new Integer(7));
		temp.setCCSID(null);
		temp.setTableSchema(schema);
		temp.setColumnDefault("0");
		temp.setCharacterMaximumLength(null);
		temp.setCharacterOctetLength(null);
		temp.setNumericPrecisionRadix(new Integer(10));
		temp.setDateTimePrecision(null);
		temp.setColumnText("PRICE CHANGE DATE");
		temp.setSystemColumnName("DAPCDT");
		temp.setSystemTableName("INDATEP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDATEPColumn12(ArrayList<ColumnInfo> result, String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DAFLG1");
		temp.setTableName("INDATEP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(12);
		temp.setDataType(ColumnInfo.CHAR);
		temp.setLength(1);
		temp.setNumericScale(null);
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("FLG1");
		temp.setStorage(1);
		temp.setNumericPrecision(null);
		temp.setCCSID(new Integer(37));
		temp.setTableSchema(schema);
		temp.setColumnDefault(" ");
		temp.setCharacterMaximumLength(new Integer(1));
		temp.setCharacterOctetLength(new Integer(1));
		temp.setNumericPrecisionRadix(null);
		temp.setDateTimePrecision(null);
		temp.setColumnText("Y=PERIOD 13 HAS A WEEK 5");
		temp.setSystemColumnName("DAFLG1");
		temp.setSystemTableName("INDATEP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDATEPColumn13(ArrayList<ColumnInfo> result, String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DAFLG2");
		temp.setTableName("INDATEP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(13);
		temp.setDataType(ColumnInfo.CHAR);
		temp.setLength(1);
		temp.setNumericScale(null);
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("FLG2");
		temp.setStorage(1);
		temp.setNumericPrecision(null);
		temp.setCCSID(new Integer(37));
		temp.setTableSchema(schema);
		temp.setColumnDefault(" ");
		temp.setCharacterMaximumLength(new Integer(1));
		temp.setCharacterOctetLength(new Integer(1));
		temp.setNumericPrecisionRadix(null);
		temp.setDateTimePrecision(null);
		temp.setColumnText("MISCELLANEOUS FLAG");
		temp.setSystemColumnName("DAFLG2");
		temp.setSystemTableName("INDATEP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDATEPColumn14(ArrayList<ColumnInfo> result, String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DAFLG3");
		temp.setTableName("INDATEP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(14);
		temp.setDataType(ColumnInfo.CHAR);
		temp.setLength(1);
		temp.setNumericScale(null);
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("FLG3");
		temp.setStorage(1);
		temp.setNumericPrecision(null);
		temp.setCCSID(new Integer(37));
		temp.setTableSchema(schema);
		temp.setColumnDefault(" ");
		temp.setCharacterMaximumLength(new Integer(1));
		temp.setCharacterOctetLength(new Integer(1));
		temp.setNumericPrecisionRadix(null);
		temp.setDateTimePrecision(null);
		temp.setColumnText("MISCELLANEOUS FLAG");
		temp.setSystemColumnName("DAFLG3");
		temp.setSystemTableName("INDATEP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}
	private ColumnInfo doINDATEPColumn15(ArrayList<ColumnInfo> result, String schema) {
		ColumnInfo temp;
		temp = new ColumnInfo();
		temp.setColumnName("DAFSYR");
		temp.setTableName("INDATEP");
		temp.setTableOwner("DFTOWNER");
		temp.setOrdinalPosition(15);
		temp.setDataType(ColumnInfo.DECIMAL);
		temp.setLength(5);
		temp.setNumericScale(new Integer(0));
		temp.setIsNullable('N');
		temp.setIsUpdateable('Y');
		temp.setLongComment(null);
		temp.setHasDefault('Y');
		temp.setColumnHeading("FIS-YR          _CCYY");
		temp.setStorage(3);
		temp.setNumericPrecision(new Integer(5));
		temp.setCCSID(null);
		temp.setTableSchema(schema);
		temp.setColumnDefault("0");
		temp.setCharacterMaximumLength(null);
		temp.setCharacterOctetLength(null);
		temp.setNumericPrecisionRadix(null);
		temp.setDateTimePrecision(new Integer(10));
		temp.setColumnText("FISCAL YEAR _CCYY");
		temp.setSystemColumnName("DAFSYR");
		temp.setSystemTableName("INDATEP");
		temp.setSystemSchemaName(schema);
		temp.setUserDefinedTypeSchema(null);
		temp.setUserDefinedTypeName(null);
		temp.setIsIdentity("NO");
		temp.setIdentityGeneration(null);
		temp.setIdentityStart(null);
		temp.setIdentityIncrement(null);
		temp.setIdentityMinimum(null);
		temp.setIdentityMaximum(null);
		temp.setIdentityCache(null);
		temp.setIdentityOrder(null);
		temp.setColumnExpression(null);
		temp.setHidden('N');
		temp.setHasFieldProc('N');
		return temp;
	}

	@Override
	public List<ColumnInfo> getColumns(String tableName, String schemaName) {
		List<ColumnInfo> result = null;
		if (tableName.equalsIgnoreCase("INDATEP")){
			result = doIndatep(schemaName);
		}
		return result;
	}

}
